server:
  port: 8002
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.91.128:8001/eureka/, http://192.168.91.128:8003/eureka/
    fetch-registry: false
  server:
    #关闭自我保护模式#
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    instance-id: eureka2:8002